[package]
name = "lorri"
version = "0.1.0"
authors = [
  "Graham Christensen <graham.christensen@target.com>",
]
homepage = "https://github.com/target/lorri"
license = "Apache-2.0"
edition = "2018"

[dependencies]
atomicwrites = "0.2.3"
bincode = "1.1.3"
crossbeam-channel = "0.3.8"
directories = "1.0.2"
lazy_static = "1.2.0"
md5  = "0.6.1"
nix = "0.14.0"
notify = "5.0.0-pre.1"
proptest = "0.9.1"
regex = "1.1.0"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
structopt = "0.2"
slog = "2.5.2"
slog-async = "2.3.0"
slog-scope = "4.3.0"
slog-term = "2.4.2"
tempfile = "3.0.7"
varlink = "10.0.0"
vec1 = "1.1.0"

# pinned to a git commit pending v2.0 release
# see: https://github.com/rust-cli/human-panic/issues/46
human-panic = { git = "https://github.com/rust-cli/human-panic.git", rev = "70db9489" }

# As of 2019-12-11, varlink_derive sets "proc_macro = true" in its Cargo.toml [1].
# Carnix does not understand this directive, it only supports "proc-macro = true" [2].
# So we use a fork with "proc-macro = true" in place of "proc_macro = true" until either
# Carnix is fixed [2] or this PR is merged into varlink_derive proper [3].
# [1] https://github.com/varlink/rust/blob/04b2a5a4/varlink_derive/Cargo.toml#L13
# [2] https://nest.pijul.com/pmeunier/carnix/discussions/41
# [3] https://github.com/varlink/rust/pull/32
varlink_derive = { git = "https://github.com/curiousleo/varlink-rust.git", rev = "88bffab5" }
